### ISSUE TITLE
question Ex 10 chapter 9

### ISSUE THREAD

**Issue by arademaker** [leanprover/logic_and_proof#17]
Ex 10 in  https://leanprover.github.io/logic_and_proof/first_order_logic_in_lean.html#equality-and-calculational-proofs

Should the first sorry in the code be replaced by a proof or not?

**Comment by avigad** [comment]
Indeed, the examples only illustrate the patterns. In practice, there will be other assumptions and `x` and `y`  can be complex terms. The first example is meant to show that if you can prove `x = y` one way or another, you can then use symmetry to prove `y = x`.
