### ISSUE TITLE
Exercises cap 5

### ISSUE THREAD

**Issue by arademaker** [leanprover/logic_and_proof#25]
https://leanprover.github.io/logic_and_proof/classical_reasoning.html#exercises

Exercise 5 is the same as the second example of 9. Maybe 5 is about drawing the ND proof on a paper and 9 is its implementation in Lean? Maybe is better to make it clear?

**Comment by avigad** [comment]
We consistently use the phrase "natural deduction proof" for the pen-and-paper diagrams, and when we say "give a natural deduction proof," we always mean that. We never use "natural deduction proof" with Lean. In this block of exercises, I think it is reasonably clear from the previous chapters and the context, and the fact that the Lean exercises come last, and have the code window.
