### ISSUE TITLE
sets in chapter 12

### ISSUE THREAD

**Issue by arademaker** [leanprover/logic_and_proof#32]
mem_inter, not_mem_empty and mem_union_left do not exists anymore!

**Comment by arademaker** [comment]
It seems that almost all theorems from Lean2 were not translated to Lean3. I found the definitions searching in the repository, for example

https://github.com/leanprover/lean2/search?q=union_distrib_right&unscoped_q=union_distrib_right

But `take` and `ext` seems fundamental. Any direction about what replaced `take` and how to define `ext`?

**Comment by avigad** [comment]
`take` is now `assume`. `ext` is now `set.ext`. The distributivity laws are in `mathlib` in the file `data/set/basic.lean`. They have names like `inter_distrib_left`, `inter_distrib_right`, `union_distrib_left`, `union_distrib_right`.

The book version of Lean is not fully up to date, and uses only a small portion of a (past) version of mathlib. At some point they should be resynchronized. But don't use Logic and Proof as a reference for Lean. Eventually, we will have better documentation for mathlib, but for now, the best way to learn what is there is by browsing the theories.

**Comment by avigad** [comment]
One day, we'll expand the text and update to a newer version of the library, but for now, I will close this.

**Comment by arademaker** [comment]
During the classes, I avoided using any mathlib code. It worked fine withot it.
