### ISSUE TITLE
relations: last proof sec 13.1

### ISSUE THREAD

**Issue by arademaker** [leanprover/logic_and_proof#39]
https://leanprover.github.io/logic_and_proof/relations.html

> **Theorem.** Suppose :math:`\leq` is a partial order on a domain :math:`A`. Define :math:`a < b` to mean that :math:`a \leq b` and :math:`a \neq b`. Then :math:`<` is a strict partial order. Moreover, if :math:`\leq` is total, so is :math:`<`.

The second paragraph of the proof of the above theorem says

> To show transitivity, suppose :math:`a < b` and :math:`b < c`. Then we have :math:`a \leq b`, :math:`b \leq c`, :math:`a \neq b`, and :math:`b \neq c`. By the transitivity of :math:`\leq`, we have :math:`a \leq c`. To show :math:`a < c`, we only have to show :math:`a \neq c`. So suppose :math:`a = c`. then, from the hypotheses, we have :math:`c < b` and :math:`b < c`, violating asymmetry. So :math:`a \neq c`, as required.

I believe this proof is wrong; we can't use the asymmetry of <. This property was proved using the transitivity of this relation, the one we are trying to prove. A possible alternative would be:

> To show transitivity, suppose :math:`a < b` and :math:`b < c`. Then we have :math:`a \leq b`, :math:`b \leq c`, :math:`a \neq b`, and :math:`b \neq c`. By the transitivity of :math:`\leq`, we have :math:`a \leq c`. To show :math:`a < c`, we only have to show :math:`a \neq c`. So suppose :math:`a = c`. then, from the hypotheses, we have :math:`c < b` and :math:`b < c`, and by the definition :math:`<` we have :math:`c \leq b`, :math`b\leq c`, :math:`c\neq b` and :math:`b\neq c` which violates the antisymmetry of :math:`\leq`. So :math:`a \neq c`, as required.

Does it make sense?

**Comment by avigad** [comment]
Good catch!
