### ISSUE TITLE
Missing proof in Section 7.3

### ISSUE THREAD

**Issue by oddg** [leanprover/logic_and_proof#43]
The section [mentions](https://github.com/leanprover/logic_and_proof/blame/master/first_order_logic.rst#L260-L262):

> In the following example, we show that if 𝐴(𝑥) always implies ¬𝐵(𝑥), then there cannot be an 𝑥 for which both 𝐴(𝑥) and 𝐵(𝑥) holds.

Then a new paragraph starts with

> There is a restriction on the term 𝑡 that appears in the elimination rule for the universal quantifier and the introduction rule for the existential quantifier, namely, that no variable that appears in 𝑡 becomes bound when you plug it in for 𝑥.

So it seems like the proof between the two paragraphs is missing.

**Comment by avigad** [comment]
@oddg Thank you very much for this correction. We moved the example to the next chapter, but forgot to delete that sentence. I have fixed it now.
