### ISSUE TITLE
Minor typographical errors in Chapter 4: Propositional Logic in Lean

### ISSUE THREAD

**Issue by Antony74** [leanprover/logic_and_proof#5]
* Pdf page 25 - missing backslashes in Ascii column of table (these need escaping)
* Pdf page 26, 3rd paragraph - "Building proofs is then a matter of writing down expressions of the write type".  Was probably intended to say "right type", suggest "correct type" is less ambigious.
* Pdf page 30 - "and introduction" and "or introduction" should probably be hyphenated for readability ("and"/"or" in the natural deduction sense of the word, not the natural language sense of the word), and for consistency with chapter 3.

Also see my attempts to address these issues in f8e4d4ef27400270c8157f161110962bac87e8f8 and 01335a7b34e6c8fea1eefb9dad9d45327079abd4.

**Comment by avigad** [comment]
@Antony74 Thank you very much for these corrections. I am sorry it took us so long to incorporate them. They got lost in my mailbox, and I just noticed them today.

**Comment by Antony74** [comment]
No worries, that looks great, thanks.

In the meantime I've been making some exercises in propositional logic interactive, by the way.
https://antony74.github.io/lean-web-editor/dist/#/
